In [22]:
# import Bibliotecas

import pandas as pd
import numpy as np

In [23]:
# abrir portfolio

df_portfolio = pd.read_csv(r'/home/ricardo/Documents/Projects/analise_alm/data/base_clientes_varejo_simulada.csv')

df_portfolio.head()

,ID_Contrato,Produto,Valor_Nocional,Taxa_Contratada_AA,Prazo_Remanescente_Meses,Indexador,Rating_2682,Dias_Atraso
0,1001,Parcelado_Loja,23774.04,0.2138,42,POS-CDI,AA,0
1,1002,Emprestimo_Pessoal,37341.81,0.1830,21,PRE,AA,0
2,1003,Parcelado_Loja,43655.72,0.2419,35,PRE,A,0
3,1004,Parcelado_Loja,21965.94,0.2565,41,PRE,A,0
4,1005,Emprestimo_Pessoal,2661.25,0.1226,40,POS-CDI,AA,0

1. ID_Contrato

O que é: Identificador único da operação.

Utilidade no Risco: Serve para rastrear a evolução do crédito ao longo do tempo (safras) e garantir que não haja duplicidade no cálculo do RWA.

2. Produto

O que é: Categoria do crédito (Emprestimo_Pessoal, Cartao_Credito, Parcelado_Loja).

Utilidade no Risco: Diferentes produtos possuem diferentes RWs (Risk Weights) para o capital regulatório e comportamentos de inadimplência distintos.

3. Valor_Nocional

O que é: O saldo devedor atual (principal + juros acruados).

Utilidade no Risco: É a base para o cálculo da EAD (Exposure at Default). No cálculo do EVE, este é o valor que será projetado e trazido a valor presente.

4. Taxa_Contratada_AA

O que é: Taxa de juros anual (Anualizada) acordada com o cliente no momento da assinatura.

Utilidade no Risco: Define a geração de receita (NII). Se a taxa contratada for fixa (PRE) e o custo de captação subir, essa coluna revela o risco de compressão da margem.

5. Prazo_Remanescente_Meses

O que é: Quantos meses faltam para o contrato encerrar.

Utilidade no Risco: Crucial para o cálculo do EVE e Duration. Quanto maior o prazo, mais sensível o valor desse contrato é a mudanças na taxa de juros (maior risco de mercado).

6. Indexador

O que é: Define se o contrato é PRE (taxa fixa) ou POS-CDI (taxa que oscila com a Selic).

Utilidade no Risco: Essencial para o Gap de Reprecificação. Contratos PRE geram risco de descasamento em cenários de alta de juros; contratos POS protegem o NII, mas podem aumentar a inadimplência se o cliente não aguentar a subida da parcela.

7. Rating_2682

O que é: Nota de crédito baseada na Resolução CMN 2.682 (AA a H).

Utilidade no Risco: Define o percentual de Provisão que o banco deve manter. Um Rating 'H' exige 100% de reserva, enquanto um 'AA' exige 0%.

8. Dias_Atraso

O que é: Há quantos dias o cliente não paga a parcela vencida.

Utilidade no Risco: É o principal driver para a mudança automática de Rating e impacto imediato no P&L através das perdas de crédito (provisões).

In [24]:
df_portfolio.describe()

,ID_Contrato,Valor_Nocional,Taxa_Contratada_AA,Prazo_Remanescente_Meses,Dias_Atraso
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,2000.500000,25327.581660,0.209143,23.818000,5.290000
std,577.494589,14145.097483,0.051683,13.441697,22.191488
min,1001.000000,509.330000,0.120000,1.000000,0.000000
25%,1500.750000,13037.482500,0.164975,12.000000,0.000000
50%,2000.500000,25843.165000,0.208950,24.000000,0.000000
75%,2500.250000,37549.010000,0.254225,36.000000,0.000000
max,3000.000000,49985.830000,0.299600,47.000000,200.000000

In [25]:
# analise de ID_contrato

vazios = len(df_portfolio['ID_Contrato']) - df_portfolio['ID_Contrato'].count()
print(rf'existem {vazios} celulas vazias de ID')

if df_portfolio['ID_Contrato'].is_unique:
    print('Nao ha dados duplicados')
else:
    print('Ha dados duplicados')

existem 0 celulas vazias de ID
Nao ha dados duplicados

In [26]:
# analise de produtos

vazios = len(df_portfolio['Produto']) - df_portfolio['Produto'].count()
print(rf'existem {vazios} celulas vazias em produtos')

x = df_portfolio['Produto'].drop_duplicates()
x

existem 0 celulas vazias em produtos

0        Parcelado_Loja
1    Emprestimo_Pessoal
7        Cartao_Credito
Name: Produto, dtype: str

In [27]:
# analise de Valor_Nocional

# vazios
vazios = len(df_portfolio['Valor_Nocional']) - df_portfolio['Valor_Nocional'].count()
print(rf'existem {vazios} celulas vazias em Valor_Nocional')

# maximo
max = df_portfolio['Valor_Nocional'].max()
print(max)

# minimo
min = df_portfolio['Valor_Nocional'].min()
print(min)

# media
media = df_portfolio['Valor_Nocional'].mean()
print(media)

# mediana
mediana = df_portfolio['Valor_Nocional'].median()
print(mediana)

existem 0 celulas vazias em Valor_Nocional
49985.83
509.33
25327.58166
25843.165